spring:
  application:
    name: SandboxTechTask
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      encoding: UTF-8

---

spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml